# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/samet/PycharmProjects/pythonProject/kontrolPaneli.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(461, 809)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        Form.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        Form.setFont(font)
        Form.setAutoFillBackground(False)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(290, 10, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 90, 442, 712))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.teamArea_1 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.teamArea_1.setMinimumSize(QtCore.QSize(440, 65))
        self.teamArea_1.setMaximumSize(QtCore.QSize(440, 65))
        self.teamArea_1.setBaseSize(QtCore.QSize(440, 65))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.teamArea_1.setFont(font)
        self.teamArea_1.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.teamArea_1.setObjectName("teamArea_1")
        self.colorPicker_1 = QtWidgets.QComboBox(self.teamArea_1)
        self.colorPicker_1.setGeometry(QtCore.QRect(10, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.colorPicker_1.setFont(font)
        self.colorPicker_1.setObjectName("colorPicker_1")
        self.colorPicker_1.addItem("")
        self.colorPicker_1.addItem("")
        self.colorPicker_1.addItem("")
        self.colorPicker_1.addItem("")
        self.colorPicker_1.addItem("")
        self.colorPicker_1.addItem("")
        self.colorPicker_1.addItem("")
        self.colorPicker_1.addItem("")
        self.colorPicker_1.addItem("")
        self.colorPicker_1.addItem("")
        self.colorPicker_1.addItem("")
        self.colorPicker_1.addItem("")
        self.colorPicker_1.addItem("")
        self.teamScore_1 = QtWidgets.QLineEdit(self.teamArea_1)
        self.teamScore_1.setGeometry(QtCore.QRect(250, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.teamScore_1.setFont(font)
        self.teamScore_1.setAlignment(QtCore.Qt.AlignCenter)
        self.teamScore_1.setObjectName("teamScore_1")
        self.incBt_1 = QtWidgets.QPushButton(self.teamArea_1)
        self.incBt_1.setGeometry(QtCore.QRect(300, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.incBt_1.setFont(font)
        self.incBt_1.setIconSize(QtCore.QSize(16, 16))
        self.incBt_1.setObjectName("incBt_1")
        self.decBt_1 = QtWidgets.QPushButton(self.teamArea_1)
        self.decBt_1.setGeometry(QtCore.QRect(370, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decBt_1.setFont(font)
        self.decBt_1.setIconSize(QtCore.QSize(16, 16))
        self.decBt_1.setObjectName("decBt_1")
        self.teamName_1 = QtWidgets.QLineEdit(self.teamArea_1)
        self.teamName_1.setGeometry(QtCore.QRect(120, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.teamName_1.setFont(font)
        self.teamName_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.teamName_1.setObjectName("teamName_1")
        self.verticalLayout.addWidget(self.teamArea_1)
        self.teamArea_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.teamArea_2.setMinimumSize(QtCore.QSize(440, 65))
        self.teamArea_2.setMaximumSize(QtCore.QSize(440, 65))
        self.teamArea_2.setBaseSize(QtCore.QSize(440, 65))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.teamArea_2.setFont(font)
        self.teamArea_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.teamArea_2.setObjectName("teamArea_2")
        self.colorPicker_2 = QtWidgets.QComboBox(self.teamArea_2)
        self.colorPicker_2.setGeometry(QtCore.QRect(10, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.colorPicker_2.setFont(font)
        self.colorPicker_2.setObjectName("colorPicker_2")
        self.colorPicker_2.addItem("")
        self.colorPicker_2.addItem("")
        self.colorPicker_2.addItem("")
        self.colorPicker_2.addItem("")
        self.colorPicker_2.addItem("")
        self.colorPicker_2.addItem("")
        self.colorPicker_2.addItem("")
        self.colorPicker_2.addItem("")
        self.colorPicker_2.addItem("")
        self.colorPicker_2.addItem("")
        self.colorPicker_2.addItem("")
        self.colorPicker_2.addItem("")
        self.colorPicker_2.addItem("")
        self.teamScore_2 = QtWidgets.QLineEdit(self.teamArea_2)
        self.teamScore_2.setGeometry(QtCore.QRect(250, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.teamScore_2.setFont(font)
        self.teamScore_2.setAlignment(QtCore.Qt.AlignCenter)
        self.teamScore_2.setObjectName("teamScore_2")
        self.incBt_2 = QtWidgets.QPushButton(self.teamArea_2)
        self.incBt_2.setGeometry(QtCore.QRect(300, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.incBt_2.setFont(font)
        self.incBt_2.setIconSize(QtCore.QSize(16, 16))
        self.incBt_2.setObjectName("incBt_2")
        self.decBt_2 = QtWidgets.QPushButton(self.teamArea_2)
        self.decBt_2.setGeometry(QtCore.QRect(370, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decBt_2.setFont(font)
        self.decBt_2.setIconSize(QtCore.QSize(16, 16))
        self.decBt_2.setObjectName("decBt_2")
        self.teamName_2 = QtWidgets.QLineEdit(self.teamArea_2)
        self.teamName_2.setGeometry(QtCore.QRect(120, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.teamName_2.setFont(font)
        self.teamName_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.teamName_2.setObjectName("teamName_2")
        self.verticalLayout.addWidget(self.teamArea_2)
        self.teamArea_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.teamArea_3.setMinimumSize(QtCore.QSize(440, 65))
        self.teamArea_3.setMaximumSize(QtCore.QSize(440, 65))
        self.teamArea_3.setBaseSize(QtCore.QSize(440, 65))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.teamArea_3.setFont(font)
        self.teamArea_3.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.teamArea_3.setObjectName("teamArea_3")
        self.colorPicker_3 = QtWidgets.QComboBox(self.teamArea_3)
        self.colorPicker_3.setGeometry(QtCore.QRect(10, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.colorPicker_3.setFont(font)
        self.colorPicker_3.setObjectName("colorPicker_3")
        self.colorPicker_3.addItem("")
        self.colorPicker_3.addItem("")
        self.colorPicker_3.addItem("")
        self.colorPicker_3.addItem("")
        self.colorPicker_3.addItem("")
        self.colorPicker_3.addItem("")
        self.colorPicker_3.addItem("")
        self.colorPicker_3.addItem("")
        self.colorPicker_3.addItem("")
        self.colorPicker_3.addItem("")
        self.colorPicker_3.addItem("")
        self.colorPicker_3.addItem("")
        self.colorPicker_3.addItem("")
        self.teamScore_3 = QtWidgets.QLineEdit(self.teamArea_3)
        self.teamScore_3.setGeometry(QtCore.QRect(250, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.teamScore_3.setFont(font)
        self.teamScore_3.setAlignment(QtCore.Qt.AlignCenter)
        self.teamScore_3.setObjectName("teamScore_3")
        self.incBt_3 = QtWidgets.QPushButton(self.teamArea_3)
        self.incBt_3.setGeometry(QtCore.QRect(300, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.incBt_3.setFont(font)
        self.incBt_3.setIconSize(QtCore.QSize(16, 16))
        self.incBt_3.setObjectName("incBt_3")
        self.decBt_3 = QtWidgets.QPushButton(self.teamArea_3)
        self.decBt_3.setGeometry(QtCore.QRect(370, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decBt_3.setFont(font)
        self.decBt_3.setIconSize(QtCore.QSize(16, 16))
        self.decBt_3.setObjectName("decBt_3")
        self.teamName_3 = QtWidgets.QLineEdit(self.teamArea_3)
        self.teamName_3.setGeometry(QtCore.QRect(120, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.teamName_3.setFont(font)
        self.teamName_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.teamName_3.setObjectName("teamName_3")
        self.verticalLayout.addWidget(self.teamArea_3)
        self.teamArea_4 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.teamArea_4.setMinimumSize(QtCore.QSize(440, 65))
        self.teamArea_4.setMaximumSize(QtCore.QSize(440, 65))
        self.teamArea_4.setBaseSize(QtCore.QSize(440, 65))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.teamArea_4.setFont(font)
        self.teamArea_4.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.teamArea_4.setObjectName("teamArea_4")
        self.colorPicker_4 = QtWidgets.QComboBox(self.teamArea_4)
        self.colorPicker_4.setGeometry(QtCore.QRect(10, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.colorPicker_4.setFont(font)
        self.colorPicker_4.setObjectName("colorPicker_4")
        self.colorPicker_4.addItem("")
        self.colorPicker_4.addItem("")
        self.colorPicker_4.addItem("")
        self.colorPicker_4.addItem("")
        self.colorPicker_4.addItem("")
        self.colorPicker_4.addItem("")
        self.colorPicker_4.addItem("")
        self.colorPicker_4.addItem("")
        self.colorPicker_4.addItem("")
        self.colorPicker_4.addItem("")
        self.colorPicker_4.addItem("")
        self.colorPicker_4.addItem("")
        self.colorPicker_4.addItem("")
        self.teamScore_4 = QtWidgets.QLineEdit(self.teamArea_4)
        self.teamScore_4.setGeometry(QtCore.QRect(250, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.teamScore_4.setFont(font)
        self.teamScore_4.setAlignment(QtCore.Qt.AlignCenter)
        self.teamScore_4.setObjectName("teamScore_4")
        self.incBt_4 = QtWidgets.QPushButton(self.teamArea_4)
        self.incBt_4.setGeometry(QtCore.QRect(300, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.incBt_4.setFont(font)
        self.incBt_4.setIconSize(QtCore.QSize(16, 16))
        self.incBt_4.setObjectName("incBt_4")
        self.decBt_4 = QtWidgets.QPushButton(self.teamArea_4)
        self.decBt_4.setGeometry(QtCore.QRect(370, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decBt_4.setFont(font)
        self.decBt_4.setIconSize(QtCore.QSize(16, 16))
        self.decBt_4.setObjectName("decBt_4")
        self.teamName_4 = QtWidgets.QLineEdit(self.teamArea_4)
        self.teamName_4.setGeometry(QtCore.QRect(120, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.teamName_4.setFont(font)
        self.teamName_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.teamName_4.setObjectName("teamName_4")
        self.verticalLayout.addWidget(self.teamArea_4)
        self.teamArea_5 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.teamArea_5.setMinimumSize(QtCore.QSize(440, 65))
        self.teamArea_5.setMaximumSize(QtCore.QSize(440, 65))
        self.teamArea_5.setBaseSize(QtCore.QSize(440, 65))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.teamArea_5.setFont(font)
        self.teamArea_5.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.teamArea_5.setObjectName("teamArea_5")
        self.colorPicker_5 = QtWidgets.QComboBox(self.teamArea_5)
        self.colorPicker_5.setGeometry(QtCore.QRect(10, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.colorPicker_5.setFont(font)
        self.colorPicker_5.setObjectName("colorPicker_5")
        self.colorPicker_5.addItem("")
        self.colorPicker_5.addItem("")
        self.colorPicker_5.addItem("")
        self.colorPicker_5.addItem("")
        self.colorPicker_5.addItem("")
        self.colorPicker_5.addItem("")
        self.colorPicker_5.addItem("")
        self.colorPicker_5.addItem("")
        self.colorPicker_5.addItem("")
        self.colorPicker_5.addItem("")
        self.colorPicker_5.addItem("")
        self.colorPicker_5.addItem("")
        self.colorPicker_5.addItem("")
        self.teamScore_5 = QtWidgets.QLineEdit(self.teamArea_5)
        self.teamScore_5.setGeometry(QtCore.QRect(250, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.teamScore_5.setFont(font)
        self.teamScore_5.setAlignment(QtCore.Qt.AlignCenter)
        self.teamScore_5.setObjectName("teamScore_5")
        self.incBt_5 = QtWidgets.QPushButton(self.teamArea_5)
        self.incBt_5.setGeometry(QtCore.QRect(300, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.incBt_5.setFont(font)
        self.incBt_5.setIconSize(QtCore.QSize(16, 16))
        self.incBt_5.setObjectName("incBt_5")
        self.decBt_5 = QtWidgets.QPushButton(self.teamArea_5)
        self.decBt_5.setGeometry(QtCore.QRect(370, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decBt_5.setFont(font)
        self.decBt_5.setIconSize(QtCore.QSize(16, 16))
        self.decBt_5.setObjectName("decBt_5")
        self.teamName_5 = QtWidgets.QLineEdit(self.teamArea_5)
        self.teamName_5.setGeometry(QtCore.QRect(120, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.teamName_5.setFont(font)
        self.teamName_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.teamName_5.setObjectName("teamName_5")
        self.verticalLayout.addWidget(self.teamArea_5)
        self.teamArea_6 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.teamArea_6.setMinimumSize(QtCore.QSize(440, 65))
        self.teamArea_6.setMaximumSize(QtCore.QSize(440, 65))
        self.teamArea_6.setBaseSize(QtCore.QSize(440, 65))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.teamArea_6.setFont(font)
        self.teamArea_6.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.teamArea_6.setObjectName("teamArea_6")
        self.colorPicker_6 = QtWidgets.QComboBox(self.teamArea_6)
        self.colorPicker_6.setGeometry(QtCore.QRect(10, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.colorPicker_6.setFont(font)
        self.colorPicker_6.setObjectName("colorPicker_6")
        self.colorPicker_6.addItem("")
        self.colorPicker_6.addItem("")
        self.colorPicker_6.addItem("")
        self.colorPicker_6.addItem("")
        self.colorPicker_6.addItem("")
        self.colorPicker_6.addItem("")
        self.colorPicker_6.addItem("")
        self.colorPicker_6.addItem("")
        self.colorPicker_6.addItem("")
        self.colorPicker_6.addItem("")
        self.colorPicker_6.addItem("")
        self.colorPicker_6.addItem("")
        self.colorPicker_6.addItem("")
        self.teamScore_6 = QtWidgets.QLineEdit(self.teamArea_6)
        self.teamScore_6.setGeometry(QtCore.QRect(250, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.teamScore_6.setFont(font)
        self.teamScore_6.setAlignment(QtCore.Qt.AlignCenter)
        self.teamScore_6.setObjectName("teamScore_6")
        self.incBt_6 = QtWidgets.QPushButton(self.teamArea_6)
        self.incBt_6.setGeometry(QtCore.QRect(300, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.incBt_6.setFont(font)
        self.incBt_6.setIconSize(QtCore.QSize(16, 16))
        self.incBt_6.setObjectName("incBt_6")
        self.decBt_6 = QtWidgets.QPushButton(self.teamArea_6)
        self.decBt_6.setGeometry(QtCore.QRect(370, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decBt_6.setFont(font)
        self.decBt_6.setIconSize(QtCore.QSize(16, 16))
        self.decBt_6.setObjectName("decBt_6")
        self.teamName_6 = QtWidgets.QLineEdit(self.teamArea_6)
        self.teamName_6.setGeometry(QtCore.QRect(120, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.teamName_6.setFont(font)
        self.teamName_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.teamName_6.setObjectName("teamName_6")
        self.verticalLayout.addWidget(self.teamArea_6)
        self.teamArea_7 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.teamArea_7.setMinimumSize(QtCore.QSize(440, 65))
        self.teamArea_7.setMaximumSize(QtCore.QSize(440, 65))
        self.teamArea_7.setBaseSize(QtCore.QSize(440, 65))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.teamArea_7.setFont(font)
        self.teamArea_7.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.teamArea_7.setObjectName("teamArea_7")
        self.colorPicker_7 = QtWidgets.QComboBox(self.teamArea_7)
        self.colorPicker_7.setGeometry(QtCore.QRect(10, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.colorPicker_7.setFont(font)
        self.colorPicker_7.setObjectName("colorPicker_7")
        self.colorPicker_7.addItem("")
        self.colorPicker_7.addItem("")
        self.colorPicker_7.addItem("")
        self.colorPicker_7.addItem("")
        self.colorPicker_7.addItem("")
        self.colorPicker_7.addItem("")
        self.colorPicker_7.addItem("")
        self.colorPicker_7.addItem("")
        self.colorPicker_7.addItem("")
        self.colorPicker_7.addItem("")
        self.colorPicker_7.addItem("")
        self.colorPicker_7.addItem("")
        self.colorPicker_7.addItem("")
        self.teamScore_7 = QtWidgets.QLineEdit(self.teamArea_7)
        self.teamScore_7.setGeometry(QtCore.QRect(250, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.teamScore_7.setFont(font)
        self.teamScore_7.setAlignment(QtCore.Qt.AlignCenter)
        self.teamScore_7.setObjectName("teamScore_7")
        self.incBt_7 = QtWidgets.QPushButton(self.teamArea_7)
        self.incBt_7.setGeometry(QtCore.QRect(300, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.incBt_7.setFont(font)
        self.incBt_7.setIconSize(QtCore.QSize(16, 16))
        self.incBt_7.setObjectName("incBt_7")
        self.decBt_7 = QtWidgets.QPushButton(self.teamArea_7)
        self.decBt_7.setGeometry(QtCore.QRect(370, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decBt_7.setFont(font)
        self.decBt_7.setIconSize(QtCore.QSize(16, 16))
        self.decBt_7.setObjectName("decBt_7")
        self.teamName_7 = QtWidgets.QLineEdit(self.teamArea_7)
        self.teamName_7.setGeometry(QtCore.QRect(120, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.teamName_7.setFont(font)
        self.teamName_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.teamName_7.setObjectName("teamName_7")
        self.verticalLayout.addWidget(self.teamArea_7)
        self.teamArea_8 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.teamArea_8.setMinimumSize(QtCore.QSize(440, 65))
        self.teamArea_8.setMaximumSize(QtCore.QSize(440, 65))
        self.teamArea_8.setBaseSize(QtCore.QSize(440, 65))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.teamArea_8.setFont(font)
        self.teamArea_8.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.teamArea_8.setObjectName("teamArea_8")
        self.colorPicker_8 = QtWidgets.QComboBox(self.teamArea_8)
        self.colorPicker_8.setGeometry(QtCore.QRect(10, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.colorPicker_8.setFont(font)
        self.colorPicker_8.setObjectName("colorPicker_8")
        self.colorPicker_8.addItem("")
        self.colorPicker_8.addItem("")
        self.colorPicker_8.addItem("")
        self.colorPicker_8.addItem("")
        self.colorPicker_8.addItem("")
        self.colorPicker_8.addItem("")
        self.colorPicker_8.addItem("")
        self.colorPicker_8.addItem("")
        self.colorPicker_8.addItem("")
        self.colorPicker_8.addItem("")
        self.colorPicker_8.addItem("")
        self.colorPicker_8.addItem("")
        self.colorPicker_8.addItem("")
        self.teamScore_8 = QtWidgets.QLineEdit(self.teamArea_8)
        self.teamScore_8.setGeometry(QtCore.QRect(250, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.teamScore_8.setFont(font)
        self.teamScore_8.setAlignment(QtCore.Qt.AlignCenter)
        self.teamScore_8.setObjectName("teamScore_8")
        self.incBt_8 = QtWidgets.QPushButton(self.teamArea_8)
        self.incBt_8.setGeometry(QtCore.QRect(300, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.incBt_8.setFont(font)
        self.incBt_8.setIconSize(QtCore.QSize(16, 16))
        self.incBt_8.setObjectName("incBt_8")
        self.decBt_8 = QtWidgets.QPushButton(self.teamArea_8)
        self.decBt_8.setGeometry(QtCore.QRect(370, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decBt_8.setFont(font)
        self.decBt_8.setIconSize(QtCore.QSize(16, 16))
        self.decBt_8.setObjectName("decBt_8")
        self.teamName_8 = QtWidgets.QLineEdit(self.teamArea_8)
        self.teamName_8.setGeometry(QtCore.QRect(120, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.teamName_8.setFont(font)
        self.teamName_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.teamName_8.setObjectName("teamName_8")
        self.verticalLayout.addWidget(self.teamArea_8)
        self.teamArea_9 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.teamArea_9.setMinimumSize(QtCore.QSize(440, 65))
        self.teamArea_9.setMaximumSize(QtCore.QSize(440, 65))
        self.teamArea_9.setBaseSize(QtCore.QSize(440, 65))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.teamArea_9.setFont(font)
        self.teamArea_9.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.teamArea_9.setObjectName("teamArea_9")
        self.colorPicker_9 = QtWidgets.QComboBox(self.teamArea_9)
        self.colorPicker_9.setGeometry(QtCore.QRect(10, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.colorPicker_9.setFont(font)
        self.colorPicker_9.setObjectName("colorPicker_9")
        self.colorPicker_9.addItem("")
        self.colorPicker_9.addItem("")
        self.colorPicker_9.addItem("")
        self.colorPicker_9.addItem("")
        self.colorPicker_9.addItem("")
        self.colorPicker_9.addItem("")
        self.colorPicker_9.addItem("")
        self.colorPicker_9.addItem("")
        self.colorPicker_9.addItem("")
        self.colorPicker_9.addItem("")
        self.colorPicker_9.addItem("")
        self.colorPicker_9.addItem("")
        self.colorPicker_9.addItem("")
        self.teamScore_9 = QtWidgets.QLineEdit(self.teamArea_9)
        self.teamScore_9.setGeometry(QtCore.QRect(250, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.teamScore_9.setFont(font)
        self.teamScore_9.setAlignment(QtCore.Qt.AlignCenter)
        self.teamScore_9.setObjectName("teamScore_9")
        self.incBt_9 = QtWidgets.QPushButton(self.teamArea_9)
        self.incBt_9.setGeometry(QtCore.QRect(300, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.incBt_9.setFont(font)
        self.incBt_9.setIconSize(QtCore.QSize(16, 16))
        self.incBt_9.setObjectName("incBt_9")
        self.decBt_9 = QtWidgets.QPushButton(self.teamArea_9)
        self.decBt_9.setGeometry(QtCore.QRect(370, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decBt_9.setFont(font)
        self.decBt_9.setIconSize(QtCore.QSize(16, 16))
        self.decBt_9.setObjectName("decBt_9")
        self.teamName_9 = QtWidgets.QLineEdit(self.teamArea_9)
        self.teamName_9.setGeometry(QtCore.QRect(120, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.teamName_9.setFont(font)
        self.teamName_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.teamName_9.setObjectName("teamName_9")
        self.verticalLayout.addWidget(self.teamArea_9)
        self.teamArea_10 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.teamArea_10.setMinimumSize(QtCore.QSize(440, 65))
        self.teamArea_10.setMaximumSize(QtCore.QSize(440, 65))
        self.teamArea_10.setBaseSize(QtCore.QSize(440, 65))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.teamArea_10.setFont(font)
        self.teamArea_10.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.teamArea_10.setObjectName("teamArea_10")
        self.colorPicker_10 = QtWidgets.QComboBox(self.teamArea_10)
        self.colorPicker_10.setGeometry(QtCore.QRect(10, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.colorPicker_10.setFont(font)
        self.colorPicker_10.setObjectName("colorPicker_10")
        self.colorPicker_10.addItem("")
        self.colorPicker_10.addItem("")
        self.colorPicker_10.addItem("")
        self.colorPicker_10.addItem("")
        self.colorPicker_10.addItem("")
        self.colorPicker_10.addItem("")
        self.colorPicker_10.addItem("")
        self.colorPicker_10.addItem("")
        self.colorPicker_10.addItem("")
        self.colorPicker_10.addItem("")
        self.colorPicker_10.addItem("")
        self.colorPicker_10.addItem("")
        self.colorPicker_10.addItem("")
        self.teamScore_10 = QtWidgets.QLineEdit(self.teamArea_10)
        self.teamScore_10.setGeometry(QtCore.QRect(250, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.teamScore_10.setFont(font)
        self.teamScore_10.setAlignment(QtCore.Qt.AlignCenter)
        self.teamScore_10.setObjectName("teamScore_10")
        self.incBt_10 = QtWidgets.QPushButton(self.teamArea_10)
        self.incBt_10.setGeometry(QtCore.QRect(300, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.incBt_10.setFont(font)
        self.incBt_10.setIconSize(QtCore.QSize(16, 16))
        self.incBt_10.setObjectName("incBt_10")
        self.decBt_10 = QtWidgets.QPushButton(self.teamArea_10)
        self.decBt_10.setGeometry(QtCore.QRect(370, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.decBt_10.setFont(font)
        self.decBt_10.setIconSize(QtCore.QSize(16, 16))
        self.decBt_10.setObjectName("decBt_10")
        self.teamName_10 = QtWidgets.QLineEdit(self.teamArea_10)
        self.teamName_10.setGeometry(QtCore.QRect(120, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.teamName_10.setFont(font)
        self.teamName_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.teamName_10.setObjectName("teamName_10")
        self.verticalLayout.addWidget(self.teamArea_10)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.navbarGroup = QtWidgets.QGroupBox(Form)
        self.navbarGroup.setGeometry(QtCore.QRect(10, 30, 440, 55))
        self.navbarGroup.setMinimumSize(QtCore.QSize(440, 0))
        self.navbarGroup.setMaximumSize(QtCore.QSize(440, 55))
        self.navbarGroup.setBaseSize(QtCore.QSize(440, 100))
        self.navbarGroup.setTitle("")
        self.navbarGroup.setObjectName("navbarGroup")
        self.scoreTableOpClBt = QtWidgets.QPushButton(self.navbarGroup)
        self.scoreTableOpClBt.setGeometry(QtCore.QRect(10, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.scoreTableOpClBt.setFont(font)
        self.scoreTableOpClBt.setObjectName("scoreTableOpClBt")
        self.comboBox = QtWidgets.QComboBox(self.navbarGroup)
        self.comboBox.setGeometry(QtCore.QRect(380, 10, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.navbarGroup)
        self.label_3.setGeometry(QtCore.QRect(260, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.checkBox = QtWidgets.QCheckBox(self.navbarGroup)
        self.checkBox.setGeometry(QtCore.QRect(200, 10, 51, 31))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(Form)
        self.comboBox.setCurrentIndex(9)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Yayıncı Skor Tablosu"))
        self.label_2.setText(_translate("Form", "by zdmrsamett@gmail.com"))
        self.teamArea_1.setTitle(_translate("Form", "Takım 1"))
        self.colorPicker_1.setItemText(0, _translate("Form", "Siyah"))
        self.colorPicker_1.setItemText(1, _translate("Form", "Gri"))
        self.colorPicker_1.setItemText(2, _translate("Form", "Beyaz"))
        self.colorPicker_1.setItemText(3, _translate("Form", "Mavi"))
        self.colorPicker_1.setItemText(4, _translate("Form", "Turkuaz"))
        self.colorPicker_1.setItemText(5, _translate("Form", "Kırmızı"))
        self.colorPicker_1.setItemText(6, _translate("Form", "Turuncu"))
        self.colorPicker_1.setItemText(7, _translate("Form", "Sarı"))
        self.colorPicker_1.setItemText(8, _translate("Form", "Yeşil (Açık)"))
        self.colorPicker_1.setItemText(9, _translate("Form", "Yeşil (Koyu)"))
        self.colorPicker_1.setItemText(10, _translate("Form", "Mor"))
        self.colorPicker_1.setItemText(11, _translate("Form", "Pembe"))
        self.colorPicker_1.setItemText(12, _translate("Form", "Kahverengi"))
        self.teamScore_1.setText(_translate("Form", "0"))
        self.incBt_1.setText(_translate("Form", "Arttır"))
        self.decBt_1.setText(_translate("Form", "Azalt"))
        self.teamName_1.setPlaceholderText(_translate("Form", "Oyuncu İsmi"))
        self.teamArea_2.setTitle(_translate("Form", "Takım 2"))
        self.colorPicker_2.setItemText(0, _translate("Form", "Siyah"))
        self.colorPicker_2.setItemText(1, _translate("Form", "Gri"))
        self.colorPicker_2.setItemText(2, _translate("Form", "Beyaz"))
        self.colorPicker_2.setItemText(3, _translate("Form", "Mavi"))
        self.colorPicker_2.setItemText(4, _translate("Form", "Turkuaz"))
        self.colorPicker_2.setItemText(5, _translate("Form", "Kırmızı"))
        self.colorPicker_2.setItemText(6, _translate("Form", "Turuncu"))
        self.colorPicker_2.setItemText(7, _translate("Form", "Sarı"))
        self.colorPicker_2.setItemText(8, _translate("Form", "Yeşil (Açık)"))
        self.colorPicker_2.setItemText(9, _translate("Form", "Yeşil (Koyu)"))
        self.colorPicker_2.setItemText(10, _translate("Form", "Mor"))
        self.colorPicker_2.setItemText(11, _translate("Form", "Pembe"))
        self.colorPicker_2.setItemText(12, _translate("Form", "Kahverengi"))
        self.teamScore_2.setText(_translate("Form", "0"))
        self.incBt_2.setText(_translate("Form", "Arttır"))
        self.decBt_2.setText(_translate("Form", "Azalt"))
        self.teamName_2.setPlaceholderText(_translate("Form", "Oyuncu İsmi"))
        self.teamArea_3.setTitle(_translate("Form", "Takım 3"))
        self.colorPicker_3.setItemText(0, _translate("Form", "Siyah"))
        self.colorPicker_3.setItemText(1, _translate("Form", "Gri"))
        self.colorPicker_3.setItemText(2, _translate("Form", "Beyaz"))
        self.colorPicker_3.setItemText(3, _translate("Form", "Mavi"))
        self.colorPicker_3.setItemText(4, _translate("Form", "Turkuaz"))
        self.colorPicker_3.setItemText(5, _translate("Form", "Kırmızı"))
        self.colorPicker_3.setItemText(6, _translate("Form", "Turuncu"))
        self.colorPicker_3.setItemText(7, _translate("Form", "Sarı"))
        self.colorPicker_3.setItemText(8, _translate("Form", "Yeşil (Açık)"))
        self.colorPicker_3.setItemText(9, _translate("Form", "Yeşil (Koyu)"))
        self.colorPicker_3.setItemText(10, _translate("Form", "Mor"))
        self.colorPicker_3.setItemText(11, _translate("Form", "Pembe"))
        self.colorPicker_3.setItemText(12, _translate("Form", "Kahverengi"))
        self.teamScore_3.setText(_translate("Form", "0"))
        self.incBt_3.setText(_translate("Form", "Arttır"))
        self.decBt_3.setText(_translate("Form", "Azalt"))
        self.teamName_3.setPlaceholderText(_translate("Form", "Oyuncu İsmi"))
        self.teamArea_4.setTitle(_translate("Form", "Takım 4"))
        self.colorPicker_4.setItemText(0, _translate("Form", "Siyah"))
        self.colorPicker_4.setItemText(1, _translate("Form", "Gri"))
        self.colorPicker_4.setItemText(2, _translate("Form", "Beyaz"))
        self.colorPicker_4.setItemText(3, _translate("Form", "Mavi"))
        self.colorPicker_4.setItemText(4, _translate("Form", "Turkuaz"))
        self.colorPicker_4.setItemText(5, _translate("Form", "Kırmızı"))
        self.colorPicker_4.setItemText(6, _translate("Form", "Turuncu"))
        self.colorPicker_4.setItemText(7, _translate("Form", "Sarı"))
        self.colorPicker_4.setItemText(8, _translate("Form", "Yeşil (Açık)"))
        self.colorPicker_4.setItemText(9, _translate("Form", "Yeşil (Koyu)"))
        self.colorPicker_4.setItemText(10, _translate("Form", "Mor"))
        self.colorPicker_4.setItemText(11, _translate("Form", "Pembe"))
        self.colorPicker_4.setItemText(12, _translate("Form", "Kahverengi"))
        self.teamScore_4.setText(_translate("Form", "0"))
        self.incBt_4.setText(_translate("Form", "Arttır"))
        self.decBt_4.setText(_translate("Form", "Azalt"))
        self.teamName_4.setPlaceholderText(_translate("Form", "Oyuncu İsmi"))
        self.teamArea_5.setTitle(_translate("Form", "Takım 5"))
        self.colorPicker_5.setItemText(0, _translate("Form", "Siyah"))
        self.colorPicker_5.setItemText(1, _translate("Form", "Gri"))
        self.colorPicker_5.setItemText(2, _translate("Form", "Beyaz"))
        self.colorPicker_5.setItemText(3, _translate("Form", "Mavi"))
        self.colorPicker_5.setItemText(4, _translate("Form", "Turkuaz"))
        self.colorPicker_5.setItemText(5, _translate("Form", "Kırmızı"))
        self.colorPicker_5.setItemText(6, _translate("Form", "Turuncu"))
        self.colorPicker_5.setItemText(7, _translate("Form", "Sarı"))
        self.colorPicker_5.setItemText(8, _translate("Form", "Yeşil (Açık)"))
        self.colorPicker_5.setItemText(9, _translate("Form", "Yeşil (Koyu)"))
        self.colorPicker_5.setItemText(10, _translate("Form", "Mor"))
        self.colorPicker_5.setItemText(11, _translate("Form", "Pembe"))
        self.colorPicker_5.setItemText(12, _translate("Form", "Kahverengi"))
        self.teamScore_5.setText(_translate("Form", "0"))
        self.incBt_5.setText(_translate("Form", "Arttır"))
        self.decBt_5.setText(_translate("Form", "Azalt"))
        self.teamName_5.setPlaceholderText(_translate("Form", "Oyuncu İsmi"))
        self.teamArea_6.setTitle(_translate("Form", "Takım 6"))
        self.colorPicker_6.setItemText(0, _translate("Form", "Siyah"))
        self.colorPicker_6.setItemText(1, _translate("Form", "Gri"))
        self.colorPicker_6.setItemText(2, _translate("Form", "Beyaz"))
        self.colorPicker_6.setItemText(3, _translate("Form", "Mavi"))
        self.colorPicker_6.setItemText(4, _translate("Form", "Turkuaz"))
        self.colorPicker_6.setItemText(5, _translate("Form", "Kırmızı"))
        self.colorPicker_6.setItemText(6, _translate("Form", "Turuncu"))
        self.colorPicker_6.setItemText(7, _translate("Form", "Sarı"))
        self.colorPicker_6.setItemText(8, _translate("Form", "Yeşil (Açık)"))
        self.colorPicker_6.setItemText(9, _translate("Form", "Yeşil (Koyu)"))
        self.colorPicker_6.setItemText(10, _translate("Form", "Mor"))
        self.colorPicker_6.setItemText(11, _translate("Form", "Pembe"))
        self.colorPicker_6.setItemText(12, _translate("Form", "Kahverengi"))
        self.teamScore_6.setText(_translate("Form", "0"))
        self.incBt_6.setText(_translate("Form", "Arttır"))
        self.decBt_6.setText(_translate("Form", "Azalt"))
        self.teamName_6.setPlaceholderText(_translate("Form", "Oyuncu İsmi"))
        self.teamArea_7.setTitle(_translate("Form", "Takım 7"))
        self.colorPicker_7.setItemText(0, _translate("Form", "Siyah"))
        self.colorPicker_7.setItemText(1, _translate("Form", "Gri"))
        self.colorPicker_7.setItemText(2, _translate("Form", "Beyaz"))
        self.colorPicker_7.setItemText(3, _translate("Form", "Mavi"))
        self.colorPicker_7.setItemText(4, _translate("Form", "Turkuaz"))
        self.colorPicker_7.setItemText(5, _translate("Form", "Kırmızı"))
        self.colorPicker_7.setItemText(6, _translate("Form", "Turuncu"))
        self.colorPicker_7.setItemText(7, _translate("Form", "Sarı"))
        self.colorPicker_7.setItemText(8, _translate("Form", "Yeşil (Açık)"))
        self.colorPicker_7.setItemText(9, _translate("Form", "Yeşil (Koyu)"))
        self.colorPicker_7.setItemText(10, _translate("Form", "Mor"))
        self.colorPicker_7.setItemText(11, _translate("Form", "Pembe"))
        self.colorPicker_7.setItemText(12, _translate("Form", "Kahverengi"))
        self.teamScore_7.setText(_translate("Form", "0"))
        self.incBt_7.setText(_translate("Form", "Arttır"))
        self.decBt_7.setText(_translate("Form", "Azalt"))
        self.teamName_7.setPlaceholderText(_translate("Form", "Oyuncu İsmi"))
        self.teamArea_8.setTitle(_translate("Form", "Takım 8"))
        self.colorPicker_8.setItemText(0, _translate("Form", "Siyah"))
        self.colorPicker_8.setItemText(1, _translate("Form", "Gri"))
        self.colorPicker_8.setItemText(2, _translate("Form", "Beyaz"))
        self.colorPicker_8.setItemText(3, _translate("Form", "Mavi"))
        self.colorPicker_8.setItemText(4, _translate("Form", "Turkuaz"))
        self.colorPicker_8.setItemText(5, _translate("Form", "Kırmızı"))
        self.colorPicker_8.setItemText(6, _translate("Form", "Turuncu"))
        self.colorPicker_8.setItemText(7, _translate("Form", "Sarı"))
        self.colorPicker_8.setItemText(8, _translate("Form", "Yeşil (Açık)"))
        self.colorPicker_8.setItemText(9, _translate("Form", "Yeşil (Koyu)"))
        self.colorPicker_8.setItemText(10, _translate("Form", "Mor"))
        self.colorPicker_8.setItemText(11, _translate("Form", "Pembe"))
        self.colorPicker_8.setItemText(12, _translate("Form", "Kahverengi"))
        self.teamScore_8.setText(_translate("Form", "0"))
        self.incBt_8.setText(_translate("Form", "Arttır"))
        self.decBt_8.setText(_translate("Form", "Azalt"))
        self.teamName_8.setPlaceholderText(_translate("Form", "Oyuncu İsmi"))
        self.teamArea_9.setTitle(_translate("Form", "Takım 9"))
        self.colorPicker_9.setItemText(0, _translate("Form", "Siyah"))
        self.colorPicker_9.setItemText(1, _translate("Form", "Gri"))
        self.colorPicker_9.setItemText(2, _translate("Form", "Beyaz"))
        self.colorPicker_9.setItemText(3, _translate("Form", "Mavi"))
        self.colorPicker_9.setItemText(4, _translate("Form", "Turkuaz"))
        self.colorPicker_9.setItemText(5, _translate("Form", "Kırmızı"))
        self.colorPicker_9.setItemText(6, _translate("Form", "Turuncu"))
        self.colorPicker_9.setItemText(7, _translate("Form", "Sarı"))
        self.colorPicker_9.setItemText(8, _translate("Form", "Yeşil (Açık)"))
        self.colorPicker_9.setItemText(9, _translate("Form", "Yeşil (Koyu)"))
        self.colorPicker_9.setItemText(10, _translate("Form", "Mor"))
        self.colorPicker_9.setItemText(11, _translate("Form", "Pembe"))
        self.colorPicker_9.setItemText(12, _translate("Form", "Kahverengi"))
        self.teamScore_9.setText(_translate("Form", "0"))
        self.incBt_9.setText(_translate("Form", "Arttır"))
        self.decBt_9.setText(_translate("Form", "Azalt"))
        self.teamName_9.setPlaceholderText(_translate("Form", "Oyuncu İsmi"))
        self.teamArea_10.setTitle(_translate("Form", "Takım 10"))
        self.colorPicker_10.setItemText(0, _translate("Form", "Siyah"))
        self.colorPicker_10.setItemText(1, _translate("Form", "Gri"))
        self.colorPicker_10.setItemText(2, _translate("Form", "Beyaz"))
        self.colorPicker_10.setItemText(3, _translate("Form", "Mavi"))
        self.colorPicker_10.setItemText(4, _translate("Form", "Turkuaz"))
        self.colorPicker_10.setItemText(5, _translate("Form", "Kırmızı"))
        self.colorPicker_10.setItemText(6, _translate("Form", "Turuncu"))
        self.colorPicker_10.setItemText(7, _translate("Form", "Sarı"))
        self.colorPicker_10.setItemText(8, _translate("Form", "Yeşil (Açık)"))
        self.colorPicker_10.setItemText(9, _translate("Form", "Yeşil (Koyu)"))
        self.colorPicker_10.setItemText(10, _translate("Form", "Mor"))
        self.colorPicker_10.setItemText(11, _translate("Form", "Pembe"))
        self.colorPicker_10.setItemText(12, _translate("Form", "Kahverengi"))
        self.teamScore_10.setText(_translate("Form", "0"))
        self.incBt_10.setText(_translate("Form", "Arttır"))
        self.decBt_10.setText(_translate("Form", "Azalt"))
        self.teamName_10.setPlaceholderText(_translate("Form", "Oyuncu İsmi"))
        self.scoreTableOpClBt.setText(_translate("Form", "Tabela Göster/Gizle"))
        self.comboBox.setItemText(0, _translate("Form", "1"))
        self.comboBox.setItemText(1, _translate("Form", "2"))
        self.comboBox.setItemText(2, _translate("Form", "3"))
        self.comboBox.setItemText(3, _translate("Form", "4"))
        self.comboBox.setItemText(4, _translate("Form", "5"))
        self.comboBox.setItemText(5, _translate("Form", "6"))
        self.comboBox.setItemText(6, _translate("Form", "7"))
        self.comboBox.setItemText(7, _translate("Form", "8"))
        self.comboBox.setItemText(8, _translate("Form", "9"))
        self.comboBox.setItemText(9, _translate("Form", "10"))
        self.label_3.setText(_translate("Form", "Oyuncu Sayısı:"))
        self.checkBox.setText(_translate("Form", "Skor"))

